### ISSUE TITLE
 Guard.state is nil.

### ISSUE THREAD

**Issue by dannysmith** [guard/guard#692]
I've just updated my [fork](https://github.com/dannysmith/guard-jammit) of guard-jammit to use Guard 2.10.1, and all the tests seem to be failing with errors like these:

```
  1) Guard::Jammit#initialize when no options are provided sets a default :config_path option
     Failure/Error: let(:guard)    { Guard::Jammit.new }
     NoMethodError:
       undefined method `session' for nil:NilClass
     # ./lib/guard/jammit.rb:39:in `initialize'
     # ./spec/guard/jammit_spec.rb:4:in `new'
     # ./spec/guard/jammit_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/guard/jammit_spec.rb:14:in `block (4 levels) in <top (required)>'
```

Here's the offending line in my spec:

``` ruby
describe Guard::Jammit do
  let(:guard)    { Guard::Jammit.new }
...
```

The error's obviously from guard/plugin.rb:284...

``` ruby
@group = Guard.state.session.groups.add(group_name)
```

It seem that Guard.state is nil, hence the error. I'm guessing this was introduced in 8976db6d402e93bf5b01eaefadb88ae67a5b53af. Any help would be appreciated.
