### ISSUE TITLE
2.9.0 Breaks notifications on manjaro

### ISSUE THREAD

**Issue by wulftone** [guard/guard#680]
I tried updating, and notifications no longer work.  They work fine on 2.8.2.

I did a git bisect and narrowed it down (maybe) to this commit: 2bb18d7d57783010b6437f1dfc0674b6569bd4a8

Here's my whole git bisect run:

```
$ (branch:master) » git bisect start
$ (branch:master) » git bisect bad
$ (branch:master) » git bisect good v2.8.2                                                                                           Bisecting: 33 revisions left to test after this (roughly 5 steps)
[c552fcf9b68cfedfab3371c736d0c185cdb27414] fix features on travis (use :cucumber)

$ (branch:c552fcf) » git bisect bad                                                                                                  Bisecting: 16 revisions left to test after this (roughly 4 steps)
[37194b046cecedd3c78b9252812def0b8e9c6944] fix Aruba backtrace

$ (branch:37194b0) » git bisect bad                                                                                                  Bisecting: 7 revisions left to test after this (roughly 3 steps)
[2b791557418982dc6f52a0c7f661d28e49f76762] refactor Setuper specs (Traps class)

$ (branch:2b79155) » git bisect bad                                                                                                  Bisecting: 3 revisions left to test after this (roughly 2 steps)
[3c32fb7afe4f16458529b2859b7f16a54ad123fb] increase deprecation backtrace to 5 lines

$ (branch:3c32fb7) » git bisect good                                                                                                 Bisecting: 1 revision left to test after this (roughly 1 step)
[2bb18d7d57783010b6437f1dfc0674b6569bd4a8] stub ENV and Notifier in ALL specs

$ (branch:2bb18d7) » git bisect bad                                                                                                  Bisecting: 0 revisions left to test after this (roughly 0 steps)
[1081a15a80afc2a7e7d9f044c6a07a5534ba8419] refactor Tmux

$ (branch:1081a15) » git bisect good                                                                                                 2bb18d7d57783010b6437f1dfc0674b6569bd4a8 is the first bad commit
commit 2bb18d7d57783010b6437f1dfc0674b6569bd4a8
Author: Cezary Baginski <cezary@chronomantic.net>
Date:   Sun Nov 9 01:11:51 2014 +0100

    stub ENV and Notifier in ALL specs

:040000 040000 80fdec922618b5ed1af0fd85c7092f01d1ff02e0 9da4e8925e7e3c9a86a7102ba704354288eb70eb M  lib
:040000 040000 705ca5f23e3175739cefa53ab16c7c06b9026f6b 8b2a6d85a04b3c560d5fa1faf196fdd792119bc5 M  spec
```

On 2bb18d7 I got this error, so I called that "bad" and moved on:

```
from /home/me/src/guard/lib/guard/setuper.rb:306:in `_load_guardfile': undefined method `connect' for Guard::Notifier:Module (NoMethodError)
from /home/me/src/guard/lib/guard/setuper.rb:65:in `setup'
from /home/me/src/guard/lib/guard/commander.rb:23:in `start'
from /home/me/src/guard/lib/guard/cli.rb:113:in `start'
from /home/me/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /home/me/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /home/me/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /home/me/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /home/me/src/guard/lib/guard/aruba_adapter.rb:32:in `execute'
from /home/me/src/guard/lib/guard/aruba_adapter.rb:19:in `execute!'
from /home/me/src/guard/bin/guard:11:in `<top (required)>'
from /home/me/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/bin/guard:23:in `load'
from /home/me/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/bin/guard:23:in `<main>'
```

But 2b79155 ran guard fine, it just didn't have notifications.  So it's somewhere around those commits.

Here's my `uname -a`:

```
Linux laptop 3.17.0-1-MANJARO #1 SMP PREEMPT Tue Oct 7 16:08:54 UTC 2014 x86_64 GNU/Linux
```
